import { AsyncFunction } from "../testers";

export type InternalTags =
	| "Undefined"
	| "Boolean"
	| "String"
	| "Function"
	| "Promise"
	| "Array"
	| "ArrayBuffer"
	| "SharedArrayBuffer"
	| "Int8Array"
	| "Int16Array"
	| "Int32Array"
	| "Uint8Array"
	| "Uint8ClampedArray"
	| "Uint16Array"
	| "Uint32Array"
	| "Float32Array"
	| "Float64Array"
	| "BigInt64Array"
	| "BigUint64Array"
	| "DataView"
	| "Map"
	| "Set"
	| "WeakMap"
	| "WeakSet"
	| "WeakRef"
	| "Proxy"
	| "RegExp"
	| "Error"
	| "Date"
	| "FinalizationRegistry"
	| "BigInt"
	| "Symbol"
	| "Iterator"
	| "AsyncFunction"
	| "GeneratorFunction"
	| "AsyncGeneratorFunction"
	| "Atomics"
	| "JSON"
	| "Math"
	| "Reflect"
	| "Null"
	| "Number"
	| "Generator"
	| "AsyncGenerator"
	| "Object"
	| "Intl.Collator"
	| "Intl.DateTimeFormat"
	| "Intl.ListFormat"
	| "Intl.NumberFormat"
	| "Intl.PluralRules"
	| "Intl.RelativeTimeFormat"
	| "Intl.Locale";
Proxy
export type InternalObjects =
	| Object
	| Function
	| AsyncFunction
	| Promise<unknown>
	| GeneratorFunction
	| AsyncGeneratorFunction
	| Generator
	| AsyncGenerator
	| Array<unknown>
	| ArrayBuffer
	| SharedArrayBuffer
	| Int8Array
	| Int16Array
	| Int32Array
	| Uint8Array
	| Uint8ClampedArray
	| Uint16Array
	| Uint32Array
	| Float32Array
	| Float64Array
	| BigInt64Array
	| BigUint64Array
	| DataView
	| Map<unknown, unknown>
	| Set<unknown>
	| WeakMap<WeakKey, unknown>
	| WeakSet<WeakKey>
	| WeakRef<WeakKey>
	| FinalizationRegistry<unknown>
	| Date
	| JSON
	| Math
	| Error
	| RegExp
	| Atomics
	| Intl.Collator
	| Intl.DateTimeFormat
	| Intl.ListFormat
	| Intl.NumberFormat
	| Intl.PluralRules
	| Intl.RelativeTimeFormat
	| Intl.Locale
	| Iterator<unknown>;
